openapi: 3.1.1
info:
  title: API de Livros
  description: API REST para gerenciamento de livros.
  version: 0.1.0
servers:
  - url: http://localhost:3000/
    description: Ambiente de Desenvolvimento
tags:
  - livros
paths:
  /users/register:
    post:
      summary: Registrar um novo usuário
      tags:
        - usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "José Reginaldo"
                email:
                  type: string
                  example: "jose.reginaldo@example.com"
                senha:
                  type: string
                  example: "abcd1234"
      responses:
        201:
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuário'
        400:
          description: Erro ao criar usuário ou e-mail já cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500:
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
  /users/login:
    post:
      summary: Autenticar um usuário e gerar token JWT
      tags:
        - usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "jose.reginaldo@example.com"
                senha:
                  type: string
                  example: "abcd1234"
      responses:
        200:
          description: Login bem-sucedido — token JWT gerado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        401:
          description: Credenciais inválidas (usuário ou senha incorretos)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500:
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
  /livros:
    get:
      summary: Listar todos os livros
      tags: 
        - livros
      responses:
        200:
          description: Lista de livros
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Livro'
        500: 
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
    post:
      summary: Criar um novo livro
      tags: 
        - livros
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  example: "Node.js para Iniciantes"
                autor:
                  type: string
                  example: "Pedro Marcato"
                publicadoEm:
                  type: string
                  example: "2025-11-02T00:00:00.000Z"
                  format: date
                disponivel:
                  type: boolean
                  example: true        
      responses:
        201:
          description: Livro criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livro'
        422:
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500: 
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
  /livros/{id}:
    get:
      summary: Buscar um livro por ID
      tags: 
        - livros
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: Livro encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livro'
        400:
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        404:
          description: Livro não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500: 
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
    put:
      security:
        - token_jwt: []
      summary: Atualizar um livro por ID
      tags: 
        - livros
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                disponivel:
                  type:
                    boolean
      responses:
        200:
          description: Livro atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livro'
        400:
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        404:
          description: Livro não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        422:
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500: 
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
    delete:
      summary: Excluir um livro por ID
      tags: 
        - livros
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        204:
          description: Livro excluído com sucesso
          content:
        400:
          description: ID inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        404:
          description: Livro não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
        500: 
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'
components:
  schemas:
    Usuário:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        senha: 
          type: string
    Livro:
      type: object
      properties:
        _id:
          type: string
        titulo:
          type: string
        autor:
          type: string
        publicadoEm:
          type: string
          format: date
        disponivel:
          type: boolean
    Erro:
      type: object
      properties:
        msg:
          type: string
  securitySchemes:
    token_jwt:
      type: http
      scheme: bearer
      in: header
      name: Authorization
      